# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/carloid/Documents/CppProjects/CppTests

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/carloid/Documents/CppProjects/CppTests

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carloid/Documents/CppProjects/CppTests/CMakeFiles /home/carloid/Documents/CppProjects/CppTests//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carloid/Documents/CppProjects/CppTests/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/carloid/Documents/CppProjects/CppTests/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CppTests

# Build rule for target.
CppTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CppTests
.PHONY : CppTests

# fast build rule for target.
CppTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/build
.PHONY : CppTests/fast

Source/Application/Gtk3WindowApp.o: Source/Application/Gtk3WindowApp.cpp.o

.PHONY : Source/Application/Gtk3WindowApp.o

# target to build an object file
Source/Application/Gtk3WindowApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/Gtk3WindowApp.cpp.o
.PHONY : Source/Application/Gtk3WindowApp.cpp.o

Source/Application/Gtk3WindowApp.i: Source/Application/Gtk3WindowApp.cpp.i

.PHONY : Source/Application/Gtk3WindowApp.i

# target to preprocess a source file
Source/Application/Gtk3WindowApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/Gtk3WindowApp.cpp.i
.PHONY : Source/Application/Gtk3WindowApp.cpp.i

Source/Application/Gtk3WindowApp.s: Source/Application/Gtk3WindowApp.cpp.s

.PHONY : Source/Application/Gtk3WindowApp.s

# target to generate assembly for a file
Source/Application/Gtk3WindowApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/Gtk3WindowApp.cpp.s
.PHONY : Source/Application/Gtk3WindowApp.cpp.s

Source/Application/HelloWorldApp.o: Source/Application/HelloWorldApp.cpp.o

.PHONY : Source/Application/HelloWorldApp.o

# target to build an object file
Source/Application/HelloWorldApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/HelloWorldApp.cpp.o
.PHONY : Source/Application/HelloWorldApp.cpp.o

Source/Application/HelloWorldApp.i: Source/Application/HelloWorldApp.cpp.i

.PHONY : Source/Application/HelloWorldApp.i

# target to preprocess a source file
Source/Application/HelloWorldApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/HelloWorldApp.cpp.i
.PHONY : Source/Application/HelloWorldApp.cpp.i

Source/Application/HelloWorldApp.s: Source/Application/HelloWorldApp.cpp.s

.PHONY : Source/Application/HelloWorldApp.s

# target to generate assembly for a file
Source/Application/HelloWorldApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/HelloWorldApp.cpp.s
.PHONY : Source/Application/HelloWorldApp.cpp.s

Source/Application/LinearLinkedListApp.o: Source/Application/LinearLinkedListApp.cpp.o

.PHONY : Source/Application/LinearLinkedListApp.o

# target to build an object file
Source/Application/LinearLinkedListApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/LinearLinkedListApp.cpp.o
.PHONY : Source/Application/LinearLinkedListApp.cpp.o

Source/Application/LinearLinkedListApp.i: Source/Application/LinearLinkedListApp.cpp.i

.PHONY : Source/Application/LinearLinkedListApp.i

# target to preprocess a source file
Source/Application/LinearLinkedListApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/LinearLinkedListApp.cpp.i
.PHONY : Source/Application/LinearLinkedListApp.cpp.i

Source/Application/LinearLinkedListApp.s: Source/Application/LinearLinkedListApp.cpp.s

.PHONY : Source/Application/LinearLinkedListApp.s

# target to generate assembly for a file
Source/Application/LinearLinkedListApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/LinearLinkedListApp.cpp.s
.PHONY : Source/Application/LinearLinkedListApp.cpp.s

Source/Application/ThreadAsyncTaskApp.o: Source/Application/ThreadAsyncTaskApp.cpp.o

.PHONY : Source/Application/ThreadAsyncTaskApp.o

# target to build an object file
Source/Application/ThreadAsyncTaskApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/ThreadAsyncTaskApp.cpp.o
.PHONY : Source/Application/ThreadAsyncTaskApp.cpp.o

Source/Application/ThreadAsyncTaskApp.i: Source/Application/ThreadAsyncTaskApp.cpp.i

.PHONY : Source/Application/ThreadAsyncTaskApp.i

# target to preprocess a source file
Source/Application/ThreadAsyncTaskApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/ThreadAsyncTaskApp.cpp.i
.PHONY : Source/Application/ThreadAsyncTaskApp.cpp.i

Source/Application/ThreadAsyncTaskApp.s: Source/Application/ThreadAsyncTaskApp.cpp.s

.PHONY : Source/Application/ThreadAsyncTaskApp.s

# target to generate assembly for a file
Source/Application/ThreadAsyncTaskApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/ThreadAsyncTaskApp.cpp.s
.PHONY : Source/Application/ThreadAsyncTaskApp.cpp.s

Source/Application/X11OpenGLWindowApp.o: Source/Application/X11OpenGLWindowApp.cpp.o

.PHONY : Source/Application/X11OpenGLWindowApp.o

# target to build an object file
Source/Application/X11OpenGLWindowApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/X11OpenGLWindowApp.cpp.o
.PHONY : Source/Application/X11OpenGLWindowApp.cpp.o

Source/Application/X11OpenGLWindowApp.i: Source/Application/X11OpenGLWindowApp.cpp.i

.PHONY : Source/Application/X11OpenGLWindowApp.i

# target to preprocess a source file
Source/Application/X11OpenGLWindowApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/X11OpenGLWindowApp.cpp.i
.PHONY : Source/Application/X11OpenGLWindowApp.cpp.i

Source/Application/X11OpenGLWindowApp.s: Source/Application/X11OpenGLWindowApp.cpp.s

.PHONY : Source/Application/X11OpenGLWindowApp.s

# target to generate assembly for a file
Source/Application/X11OpenGLWindowApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Application/X11OpenGLWindowApp.cpp.s
.PHONY : Source/Application/X11OpenGLWindowApp.cpp.s

Source/Main.o: Source/Main.cpp.o

.PHONY : Source/Main.o

# target to build an object file
Source/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Main.cpp.o
.PHONY : Source/Main.cpp.o

Source/Main.i: Source/Main.cpp.i

.PHONY : Source/Main.i

# target to preprocess a source file
Source/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Main.cpp.i
.PHONY : Source/Main.cpp.i

Source/Main.s: Source/Main.cpp.s

.PHONY : Source/Main.s

# target to generate assembly for a file
Source/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/Main.cpp.s
.PHONY : Source/Main.cpp.s

Source/OpenGL/Shader.o: Source/OpenGL/Shader.cpp.o

.PHONY : Source/OpenGL/Shader.o

# target to build an object file
Source/OpenGL/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/OpenGL/Shader.cpp.o
.PHONY : Source/OpenGL/Shader.cpp.o

Source/OpenGL/Shader.i: Source/OpenGL/Shader.cpp.i

.PHONY : Source/OpenGL/Shader.i

# target to preprocess a source file
Source/OpenGL/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/OpenGL/Shader.cpp.i
.PHONY : Source/OpenGL/Shader.cpp.i

Source/OpenGL/Shader.s: Source/OpenGL/Shader.cpp.s

.PHONY : Source/OpenGL/Shader.s

# target to generate assembly for a file
Source/OpenGL/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/OpenGL/Shader.cpp.s
.PHONY : Source/OpenGL/Shader.cpp.s

Source/X11GLWindow.o: Source/X11GLWindow.cpp.o

.PHONY : Source/X11GLWindow.o

# target to build an object file
Source/X11GLWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/X11GLWindow.cpp.o
.PHONY : Source/X11GLWindow.cpp.o

Source/X11GLWindow.i: Source/X11GLWindow.cpp.i

.PHONY : Source/X11GLWindow.i

# target to preprocess a source file
Source/X11GLWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/X11GLWindow.cpp.i
.PHONY : Source/X11GLWindow.cpp.i

Source/X11GLWindow.s: Source/X11GLWindow.cpp.s

.PHONY : Source/X11GLWindow.s

# target to generate assembly for a file
Source/X11GLWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppTests.dir/build.make CMakeFiles/CppTests.dir/Source/X11GLWindow.cpp.s
.PHONY : Source/X11GLWindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CppTests"
	@echo "... Source/Application/Gtk3WindowApp.o"
	@echo "... Source/Application/Gtk3WindowApp.i"
	@echo "... Source/Application/Gtk3WindowApp.s"
	@echo "... Source/Application/HelloWorldApp.o"
	@echo "... Source/Application/HelloWorldApp.i"
	@echo "... Source/Application/HelloWorldApp.s"
	@echo "... Source/Application/LinearLinkedListApp.o"
	@echo "... Source/Application/LinearLinkedListApp.i"
	@echo "... Source/Application/LinearLinkedListApp.s"
	@echo "... Source/Application/ThreadAsyncTaskApp.o"
	@echo "... Source/Application/ThreadAsyncTaskApp.i"
	@echo "... Source/Application/ThreadAsyncTaskApp.s"
	@echo "... Source/Application/X11OpenGLWindowApp.o"
	@echo "... Source/Application/X11OpenGLWindowApp.i"
	@echo "... Source/Application/X11OpenGLWindowApp.s"
	@echo "... Source/Main.o"
	@echo "... Source/Main.i"
	@echo "... Source/Main.s"
	@echo "... Source/OpenGL/Shader.o"
	@echo "... Source/OpenGL/Shader.i"
	@echo "... Source/OpenGL/Shader.s"
	@echo "... Source/X11GLWindow.o"
	@echo "... Source/X11GLWindow.i"
	@echo "... Source/X11GLWindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/carloid/Documents/CppProjects/CppTests/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

